node {

    stage 'Checkout'
    git branch: 'main', url: 'https://github.com/stu93303148/simple-java-maven-app.git'

    // Get the maven tool
    // ** NOTE: This 'M3' maven tool must be configured in the global configuration
    def mvnHome = tool 'M3'
    
    stage 'Build'
    sh "${mvnHome}/bin/mvn -B -DskipTests clean package"
    
    stage 'Test'
    sh "${mvnHome}/bin/mvn test"

}
